# Generated by Django 3.2 on 2021-04-27 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=20)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_losses', models.IntegerField(default=0)),
                ('mm_wins', models.IntegerField(default=0)),
                ('mm_losses', models.IntegerField(default=0)),
                ('jj_wins', models.IntegerField(default=0)),
                ('jj_losses', models.IntegerField(default=0)),
                ('ss_wins', models.IntegerField(default=0)),
                ('ss_losses', models.IntegerField(default=0)),
                ('cc_wins', models.IntegerField(default=0)),
                ('cc_losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.IntegerField(default=0)),
                ('date_time', models.DateField()),
                ('has_occurred', models.BooleanField(default=False)),
                ('teams', models.ManyToManyField(related_name='teams', to='overwatchleague.Team')),
                ('week', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='overwatchleague.week')),
            ],
        ),
    ]
