# Generated by Django 3.2 on 2021-04-27 01:37

from django.db import migrations

def create_data(apps, schema_editor):
    print()

class Migration(migrations.Migration):

    dependencies = [
        ('overwatchleague', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
