# Generated by Django 3.2 on 2021-04-27 01:58

from django.db import migrations
from ..models import Team

def create_data(apps, schema_editor):
    west_teams = {
        "outlaws": "Houston Outlaws",
        "fuel": "Dallas Fuel",
        "gladiators": "Los Angeles Gladiators",
        "shock": "San Francisco Shock",
        "defiant": "Toronto Defiant",
        "titans": "Vancouver Titans",
        "reign": "Atlanta Reign",
        "mayhem": "Florida Mayhem",
        "eternal": "Paris Eternal",
        "spitfire": "London Spitfire",
        "uprising": "Boston Uprising",
        "justice": "Washington Justice"
        }
    east_teams = {
        "charge": "Guangzhou Charge",
        "dragons": "Shanghai Dragons",
        "valiant": "Los Angeles Valiant",
        "hunters": "Chengdu Hunters",
        "fusion": "Philadelphia Fusion",
        "dynasty": "Seoul Dynasty",
        "excelsior": "New York Excelsior",
        "spark": "Hangzhou Spark"
    }
    url = "https://owlpickem.s3.us-east-2.amazonaws.com/"
    for name, full in west_teams.items():
        logo_link = url+name+".png"
        location = ' '.join(full.split(" ")[0:-1])
        n = full.split(" ")[-1]
        region = "west"
        Team(location=location, region=region, name=n, logo=logo_link).save()
    
    for name, full in east_teams.items():
        logo_link = url+name+".png"
        location = ' '.join(full.split(" ")[0:-1])
        n = full.split(" ")[-1]
        region = "east"
        Team(location=location, region=region, name=n, logo=logo_link).save()
    



class Migration(migrations.Migration):

    dependencies = [
        ('overwatchleague', '0003_team_playoff_points'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
