# Generated by Django 3.2 on 2021-04-27 04:31

from django.db import migrations
from ..models import Team, Game
import os
import csv
from datetime import datetime

def create_data(apps, schema_editor):
    teams = {
        "HOU": "Houston Outlaws",
        "DAL": "Dallas Fuel",
        "GLA": "Los Angeles Gladiators",
        "SFS": "San Francisco Shock",
        "GZC": "Guangzhou Charge",
        "SHD": "Shanghai Dragons",
        "VAL": "Los Angeles Valiant",
        "CDH": "Chengdu Hunters",
        "PHI": "Philadelphia Fusion",
        "SEO": "Seoul Dynasty",
        "TOR": "Toronto Defiant",
        "VAN": "Vancouver Titans",
        "ATL": "Atlanta Reign",
        "FLA": "Florida Mayhem",
        "PAR": "Paris Eternal",
        "LDN": "London Spitfire",
        "NYE": "New York Excelsior",
        "HZS": "Hangzhou Spark",
        "BOS": "Boston Uprising",
        "WAS": "Washington Justice"
    }

    with open('overwatchleague\migrations\schedule.csv') as f:
        reader = csv.reader(f)
        curr_game = 1
        curr_week = 1
        for row in reader:
            week = row[0]
            time = datetime.strptime(row[1], "%A %B %d %H:%M")
            time = time.replace(year=2021)
            team1 = row[2]
            team2 = row[3]

            if week != curr_week:
                curr_week = week
                curr_game = 1
            
            g = Game(week=curr_week, game_number=curr_game, date_time=time)
            g.save()

            g.teams.add(Team.objects.get(name=teams[team1].split(" ")[-1]))
            g.teams.add(Team.objects.get(name=teams[team2].split(" ")[-1]))

            g.save()

            curr_game += 1  

class Migration(migrations.Migration):

    dependencies = [
        ('overwatchleague', '0005_auto_20210427_0031'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
