# Generated by Django 3.2 on 2021-04-28 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overwatchleague', '0011_overwatchleague'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='cc_diff',
            new_name='tournament_diff',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='cc_losses',
            new_name='tournament_losses',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='cc_wins',
            new_name='tournament_wins',
        ),
        migrations.RemoveField(
            model_name='team',
            name='jj_diff',
        ),
        migrations.RemoveField(
            model_name='team',
            name='jj_losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='jj_wins',
        ),
        migrations.RemoveField(
            model_name='team',
            name='mm_diff',
        ),
        migrations.RemoveField(
            model_name='team',
            name='mm_losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='mm_wins',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ss_diff',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ss_losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ss_wins',
        ),
    ]
