# Generated by Django 3.2 on 2021-04-28 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwatchleague', '0012_auto_20210428_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='losing_team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='losing_team', to='overwatchleague.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='map_diff',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='winning_team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_team', to='overwatchleague.team'),
        ),
    ]
