# Generated by Django 3.2 on 2021-04-29 20:07

from django.db import migrations
from ..models import Team, Game

def create_data(apps, schema_editor):
    games = Game.objects.all()
    for game in games:
        region = game.teams.all()[0].region
        game.region = region
        game.save()

class Migration(migrations.Migration):

    dependencies = [
        ('overwatchleague', '0014_game_region'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
